version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers-legacy
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: jason  
          POSTGRES_DB: todolist_test
          POSTGRES_PASSWORD: password
          DATABASE_URL: "postgres://ubuntu@localhost:5432/todolist_test"
      - image: redis
    
    steps:
      - checkout

       # Install System Dependencies
      - run:
          name: Install System Dependencies
          command: sudo apt-get update && sudo apt-get install g++ qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x

      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run tests
          command: bundle exec rspec
