default: &default
  adapter: postgresql
  encoding: unicode
  username: jason
  password: password
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todolist_development

test:
  <<: *default
  database: todolist_test

production:
  <<: *default
  database: todolist_production
